name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libayatana-appindicator3-dev pkg-config
      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o freedom-core-linux-x64 ./cmd/server
      - uses: actions/upload-artifact@v4
        with:
          name: freedom-core-linux-x64
          path: freedom-core-linux-x64

  build-windows-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build Windows AMD64
        shell: pwsh
        run: |
          $env:GOOS="windows"
          $env:GOARCH="amd64"
          go build -ldflags "-H=windowsgui" -o freedom-core-windows-x64.exe ./cmd/server
      - uses: actions/upload-artifact@v4
        with:
          name: freedom-core-windows-x64.exe
          path: freedom-core-windows-x64.exe

  build-windows-386:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build Windows 386
        shell: pwsh
        run: |
          $env:GOOS="windows"
          $env:GOARCH="386"
          go build -ldflags "-H=windowsgui" -o freedom-core-windows-x86.exe ./cmd/server
      - uses: actions/upload-artifact@v4
        with:
          name: freedom-core-windows-x86.exe
          path: freedom-core-windows-x86.exe

  release:
    needs: [build-linux, build-windows-amd64, build-windows-386]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: freedom-core-linux-x64
          path: artifacts
      - uses: actions/download-artifact@v4
        with:
          name: freedom-core-windows-x64.exe
          path: artifacts
      - uses: actions/download-artifact@v4
        with:
          name: freedom-core-windows-x86.exe
          path: artifacts
      - name: Upload Executables to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}